os:
  - linux
language: python
sudo: true
python:
  - 2.7
env:
    - PEP8_IGNORE="E731,W503,E402"
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.pip-cache/
    - /home/travis/virtualenv/python2.7
before_install:
    - sudo apt-get update
    - sudo apt-get install libportaudio-dev libportaudio0 libportaudio2 python-pyaudio espeak festival
install: 
    - pip install -U -r python_requirement.txt
    - pip install -U python-coveralls
    - pip install coverage
    - pip install flake8
    - pip install codecov
    - pip install pep8
before_script:
    - flake8 robocop/RoboCop.py
    - git config --global user.email "olxboss@gmail.com"
    - git config --global user.name "Travis-CI"
script:
    - coverage run -m unittest discover
after_success:
    - coverage report
    - codecov --token=b7bcdcc3-478d-4ccc-871c-5896bb4c7383
    - coveralls
notifications:
  email: true
